server:
   port: 8070
   ssl:
    key-store: /home/yoonhee/cert_and_key.p12
    key-store-password: 1q2w3e4r
    key-store-type: pkcs12
    key-alias: http
spring: 
  application:
    name: userService
  datasource: 
    hikari: 
      jdbc-url: jdbc:mysql://localhost:3306/bootBoarddb?serverTimezone=UTC
      username: root
      password: 1004
      driver-class-name: com.mysql.jdbc.Driver
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
